version: '3'
services:
  essence_backend:
    image: "essencecommunity/essence-backend:2.6.1"
    volumes:
      - './dist/module:/opt/work_gate/module'
    depends_on:
      - essence_backend_db
    environment:
      POSTGRES_HOST: essence_backend_db
      POSTGRES_PORT: 5432
      POSTGRES_ADMIN_DATABASE: s_su
      POSTGRES_ADMIN_USER: s_su
      POSTGRES_ADMIN_PASSWORD: s_su
    links:
      - essence_backend_db

  essence_backend_db:
    image: "postgres:11-alpine"
    ports:
      - "10021:5432"
    environment:
      POSTGRES_PASSWORD: s_su
      POSTGRES_USER: s_su
      POSTGRES_DB: s_su

  essence_frontend:
    image: "essencecommunity/essence-frontend:2.6.1"
    depends_on:
      - essence_backend
    volumes:
      - './dist/module:/opt/module'
    environment:
      ESSENCE_BACKEND_HOST: essence_backend
      ESSENCE_BACKEND_PORT: 8080
    ports:
      - "10020:80"
    links:
      - essence_backend
