apiVersion: v1
kind: Namespace
metadata:
  name: essence
---
apiVersion: v1
kind: Secret
metadata:
  name: essence-secret
  namespace: essence
type: Opaque
data:
  super_admin_user: c19zdQ==
  super_admin_password: c19zdQ==
  super_admin_db: c19zdQ==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: essence-store-module-pv
  namespace: essence
  labels:
    type: local
spec:
  storageClassName: module-essence
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/module_essence"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: essence
  name: essence-store-module-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: module-essence
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: essence-store-pg-data-pv
  namespace: essence
  labels:
    type: local
spec:
  storageClassName: pg-data
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/pg_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: essence
  name: essence-store-pg-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: pg-data
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: essence
  name: essence-backend-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: essence-backend-db
  strategy: {}
  template:
    metadata:
      namespace: essence
      labels:
        io.kompose.service: essence-backend-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: essence-secret
                  key: super_admin_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: essence-secret
                  key: super_admin_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: essence-secret
                  key: super_admin_user
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          image: postgres:11-alpine
          imagePullPolicy: ""
          name: essence-backend-db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: essence-store-pg-data-pvc
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: essence-store-pg-data-pvc
          persistentVolumeClaim:
            claimName: essence-store-pg-data-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: essence
  name: essence-backend-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      nodePort: 30021
  selector:
    io.kompose.service: essence-backend-db
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: essence
  name: essence-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: essence-backend
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: essence
      labels:
        io.kompose.service: essence-backend
    spec:
      containers:
        - env:
            - name: POSTGRES_ADMIN_DATABASE
              valueFrom:
                secretKeyRef:
                  name: essence-secret
                  key: super_admin_db
            - name: POSTGRES_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: essence-secret
                  key: super_admin_password
            - name: POSTGRES_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: essence-secret
                  key: super_admin_user
            - name: POSTGRES_HOST
              value: $(ESSENCE_BACKEND_DB_SERVICE_HOST)
            - name: POSTGRES_PORT
              value: $(ESSENCE_BACKEND_DB_SERVICE_PORT)
          image: essencecommunity/essence-backend:2.7.0
          imagePullPolicy: ""
          name: essence-backend
          resources: {}
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/work_gate/module
              name: essence-store-module-pvc
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: essence-store-module-pvc
          persistentVolumeClaim:
            claimName: essence-store-module-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: essence
  name: essence-backend
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: essence-backend
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: essence
  name: essence-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: essence-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: essence
      labels:
        io.kompose.service: essence-frontend
    spec:
      containers:
        - env:
            - name: ESSENCE_BACKEND_HOST
              value: $(ESSENCE_BACKEND_SERVICE_HOST)
            - name: ESSENCE_BACKEND_PORT
              value: $(ESSENCE_BACKEND_SERVICE_PORT)
          image: essencecommunity/essence-frontend:2.7.0
          imagePullPolicy: ""
          name: essence-frontend
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /opt/module
              name: essence-store-module-pvc
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: essence-store-module-pvc
          persistentVolumeClaim:
            claimName: essence-store-module-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: essence
  name: essence-frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 30020
  selector:
    io.kompose.service: essence-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
