apiVersion: v1
kind: Secret
metadata:
    name: essence-secret
    namespace: { { .Values.namespace.name } }
type: Opaque
data:
    super_admin_user: { { .Values.secrets.superAdminUser | b64enc } }
    super_admin_password: { { .Values.secrets.superAdminPassword | b64enc } }
    super_admin_db: { { .Values.secrets.superAdminDb | b64enc } }
