[[data]]
cv_description = "Локализация meta"
ck_d_plugin = "CorePgLocalization"
ck_id = "localization"

  [data.cct_params]
  poolMin = 1
  poolMax = 5
  user = "s_mc"
  password = "s_mc"
  connectString = "postgres://#POSTGRES_HOST#:#POSTGRES_PORT#/core_meta"

[[data]]
cv_description = "Оповещение meta"
ck_d_plugin = "CorePgNotification"
ck_id = "meta"

  [data.cct_params]
  poolMax = 10
  poolMin = 1
  user = "s_mc"
  password = "s_mc"
  connectString = "postgres://#POSTGRES_HOST#:#POSTGRES_PORT#/core_meta"

[[data]]
cv_description = "Семафор meta"
ck_d_plugin = "CorePgSemaphore"
ck_id = "semaphore"

  [data.cct_params]
  poolMin = 1
  poolMax = 2
  user = "s_mc"
  password = "s_mc"
  connectString = "postgres://#POSTGRES_HOST#:#POSTGRES_PORT#/core_meta"

[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
