[[data]]
ck_id = "core"
cv_path = "/api"
cv_description = "Основныенастройкиметаинформации"
ck_d_plugin = "CorePGContext"

    [data.cct_params]
    debug = true
    disableCache = true
    poolMax = 100
    connectString = "postgres://s_mc:s_mc@#DB_HOST#:#DB_PORT#/#DB_PREFIX_META#meta"

[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
