[[data]]
cv_description = "Оповещение meta"
ck_d_plugin = "CorePgNotification"
ck_id = "meta"

[data.cct_params]
authProvider = "auth"
connectString = "postgres://s_su:s_su@#DB_HOST#:#DB_PORT#/core"

[[data]]
cv_description = "Семафор meta"
ck_d_plugin = "CorePgSemaphore"
ck_id = "semaphore"

[data.cct_params]
connectString = "postgres://s_su:s_su@#DB_HOST#:#DB_PORT#/core"

[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
