[[data]]
cv_description = "Оповещение meta"
ck_d_plugin = "CorePgNotification"
ck_id = "meta"

    [data.cct_params]
    authProvider = "authcore"
    connectString = "postgres://s_mc:s_mc@#DB_HOST#:#DB_PORT#/#DB_PREFIX_META#meta"

[[data]]
cv_description = "Семафор meta"
ck_d_plugin = "CorePgSemaphore"
ck_id = "semaphore"

    [data.cct_params]
    connectString = "postgres://s_mc:s_mc@#DB_HOST#:#DB_PORT#/#DB_PREFIX_META#meta"

[[data]]
cv_description = "Локализация meta"
ck_d_plugin = "CorePgLocalization"
ck_id = "localization"

    [data.cct_params]
    poolMin = 1
    poolMax = 100
    connectString = "postgres://s_mc:s_mc@#DB_HOST#:#DB_PORT#/#DB_PREFIX_META#meta"

[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
