[[data]]
cv_name = "preparequery"
cv_description = "Плагин преобразования запросов filter,sort"
ck_d_provider = "meta"
ck_d_plugin = "PrepareQuery"
cl_required = 1
cl_default = 0
cct_params = { }
ck_id = "PrepareQuerymeta"
cn_order = 1

[[data]]
cv_name = "extractrow"
cv_description = "Плагин распаковывания вложеного json"
ck_d_provider = "meta"
ck_d_plugin = "JsonRowColumnExtractor"
cl_required = 1
cl_default = 0
ck_id = "extractRowmeta"
cn_order = 2

[data.cct_params]
columns = "json,result"
extractSingleColumn = false

[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
