[[data]]
ck_id = "core"
cv_path = "/api"
cv_description = "Основные настройки метаинформации"
ck_d_plugin = "CorePGContext"

  [data.cct_params]
  debug = true
  disableCache = true
  poolMax = 100
  maxPostSize = 10_000_000
  user = "s_mc"
  password = "s_mc"
  connectString = "postgres://postgres:5432/core"
[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
