[[data]]
cv_description = "Локализация meta"
ck_d_plugin = "CorePgLocalization"
ck_id = "localization"

  [data.cct_params]
  poolMin = 1
  poolMax = 100
  user = "s_mc"
  password = "s_mc"
  connectString = "postgres://postgres:5432/core"

[[data]]
cv_description = "Оповещение meta"
ck_d_plugin = "CorePgNotification"
ck_id = "meta"

  [data.cct_params]
  poolMin = 1
  poolMax = 100
  user = "s_mc"
  password = "s_mc"
  connectString = "postgres://postgres:5432/core"

[[data]]
cv_description = "Семафор meta"
ck_d_plugin = "CorePgSemaphore"
ck_id = "semaphore"

  [data.cct_params]
  poolMin = 1
  poolMax = 100
  user = "s_mc"
  password = "s_mc"
  connectString = "postgres://postgres:5432/core"
[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
