[[data]]
cv_description = "Оповещение meta"
ck_d_plugin = "CorePgNotification"
ck_id = "meta"

  [data.cct_params]
  authProvider = "auth"
  poolMin = 1
  poolMax = 100
  connectString = "postgres://s_mc:s_mc@postgres:5432/core"

[[data]]
cv_description = "Семафор meta"
ck_d_plugin = "CorePgSemaphore"
ck_id = "semaphore"

  [data.cct_params]
  poolMin = 1
  poolMax = 100
  connectString = "postgres://s_mc:s_mc@postgres:5432/core"
[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
