[[data]]
cv_name = "modulestorage"
cv_description = "Место хранения модулей"
ck_d_provider = "meta"
ck_d_plugin = "modulestorage"
cl_required = 0
cl_default = 0
ck_id = "ModuleStorage:meta"
cn_order = 1

  [data.cct_params]
  cvTypeStorage = "dir"
  cvPath = "/dist/module"

[[data]]
cv_name = "preparequery"
cv_description = "Плагин преобразования запросов filter,sort"
ck_d_provider = "authcore"
ck_d_plugin = "PrepareQuery"
cl_required = 1
cl_default = 0
cct_params = { }
ck_id = "PrepareQuery:authcore"
cn_order = 1

[[data]]
cv_name = "preparequery"
cv_description = "Плагин преобразования запросов filter,sort"
ck_d_provider = "meta"
ck_d_plugin = "PrepareQuery"
cl_required = 1
cl_default = 0
cct_params = { }
ck_id = "PrepareQuery:meta"
cn_order = 1

[[data]]
cv_name = "preparequery"
cv_description = "Плагин преобразования запросов filter,sort"
ck_d_provider = "s_ic_adm"
ck_d_plugin = "PrepareQuery"
cl_required = 1
cl_default = 0
cct_params = { }
ck_id = "PrepareQuery:s_ic_adm"
cn_order = 1

[[data]]
ck_id = "create_patch:authcore"
cv_name = "create_patch"
ck_d_provider = "authcore"
ck_d_plugin = "patcher"
cl_required = 0
cn_order = 1
cl_default = 0
cv_description = "Создание патча для авторизации"

  [data.cct_params]
  cvTypeStorage = "dir"
  cvPath = "/opt/patch"

[[data]]
ck_id = "create_patch:meta"
cv_name = "create_patch"
ck_d_provider = "meta"
ck_d_plugin = "patcher"
cl_required = 0
cn_order = 1
cl_default = 0
cv_description = "Создает патч для обновление бд"

  [data.cct_params]
  cvTypeStorage = "dir"
  cvPath = "/opt/patch"

[[data]]
ck_id = "create_patch:s_ic_adm"
cv_name = "create_patch"
ck_d_provider = "s_ic_adm"
ck_d_plugin = "patcher"
cl_required = 0
cn_order = 1
cl_default = 0
cv_description = "Создает патч для обновление бд"

  [data.cct_params]
  cvTypeStorage = "dir"
  cvPath = "/opt/patch"

[[data]]
cv_name = "extractrow"
cv_description = "Плагин распаковывания вложеного json"
ck_d_provider = "authcore"
ck_d_plugin = "JsonRowColumnExtractor"
cl_required = 1
cl_default = 0
ck_id = "extractRow:authcore"
cn_order = 2

  [data.cct_params]
  extractSingleColumn = true
  columns = "json,result"

[[data]]
cv_name = "extractrow"
cv_description = "Плагин распаковывания вложеного json"
ck_d_provider = "meta"
ck_d_plugin = "JsonRowColumnExtractor"
cl_required = 1
cl_default = 0
ck_id = "extractRow:meta"
cn_order = 2

  [data.cct_params]
  extractSingleColumn = true
  columns = "json,result"

[[data]]
cv_name = "extractrow"
cv_description = "Плагин распаковывания вложеного json"
ck_d_provider = "s_ic_adm"
ck_d_plugin = "JsonRowColumnExtractor"
cl_required = 1
cl_default = 0
ck_id = "extractRow:s_ic_adm"
cn_order = 2

  [data.cct_params]
  extractSingleColumn = true
  columns = "json,result"
[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
