[[data]]
ck_id = "admingate"
cv_description = "Провайдер администрирования"
ck_d_plugin = "admingate"
cl_autoload = 0
cct_params = { }

[[data]]
ck_id = "auth"
cv_description = "Провайдер авторизации"
cl_autoload = true
ck_d_plugin = "AuthMock"

  [data.cct_params]
  adminUser = "admin_core"
  adminPassword = "123456"
  viewUser = "view_core"

[[data]]
ck_id = "authcore"
cl_autoload = 1
ck_d_plugin = "coreauthpg"
cv_description = "Провайдер внутренней авторизации"

  [data.cct_params]
  connectString = "postgres://s_ac:s_ac@postgres:5432/core_auth"
  poolMax = 10
  sessionDuration = 2_000
  onlySession = false

[[data]]
ck_id = "meta"
cv_description = "Провайдер работы с метаинформацией"
cl_autoload = true
ck_d_plugin = "PostgreSQLDb"

  [data.cct_params]
  core = true
  poolMin = 1
  poolMax = 100
  connectString = "postgres://s_su:s_su@postgres:5432/core"
[[data]]
[data."$$indexCreated"]
fieldName = "ck_id"
unique = true
sparse = false
